# ref: https://github.com/actions/runner-images
name: amd64 Windows

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        cmake: [
          {name: "VS2022", config: Release},
        ]
        java: [
          # see https://endoflife.date/azul-zulu
          {distrib: 'zulu', version: '8'}, # 2030/12
          {distrib: 'zulu', version: '11'}, # 2026/09
          {distrib: 'zulu', version: '17'}, # 2029/09
          {distrib: 'zulu', version: '21'}, # 2031/09
          # see https://endoflife.date/eclipse-temurin
          {distrib: 'temurin', version: '8'}, # 2026/11
          {distrib: 'temurin', version: '11'}, # 2027/10
          {distrib: 'temurin', version: '17'}, # 2027/10
          {distrib: 'temurin', version: '21'}, # 2029/12
          # see https://endoflife.date/microsoft-build-of-openjdk
          {distrib: 'microsoft', version: '11'}, # 2027/09
          {distrib: 'microsoft', version: '17'}, # 2027/09
          {distrib: 'microsoft', version: '21'}, # 2028/09
        ]
      fail-fast: false
    name: amd64•Windows•CMake(${{matrix.cmake.name}})•${{matrix.java.distrib}}-${{matrix.java.version}}
    runs-on: windows-latest
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{matrix.java.distrib}}
          java-version: ${{matrix.java.version}}
      - name: Check java
        run: |
          java -version
          mvn --version
      - name: Check CMake
        run: cmake --version
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -G "Visual Studio 17 2022"
          -DCMAKE_CONFIGURATION_TYPES=${{matrix.cmake.config}}
          -DCMAKE_INSTALL_PREFIX=install
          -DSKIP_GPG=ON
      - name: Build
        run: >
          cmake --build build
          --config ${{matrix.cmake.config}}
          --target ALL_BUILD
          -v -j2
      - name: Test
        run: >
          cmake --build build
          --config ${{matrix.cmake.config}}
          --target RUN_TESTS
          -v
      - name: Install
        run: >
          cmake --build build
          --config ${{matrix.cmake.config}}
          --target INSTALL
          -v -- /verbosity:diag /maxcpucount

  amd64_windows:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v4
